'@startuml
'用户登录
'前端网页->后端servlet:登录操作
'后端servlet->数据库:数据查询对应信息
'数据库->后端servlet:判断登录操作是否有效
'后端servlet->前端网页:登录有效返回token,进行页面跳转
'前端网页->后端servlet:下次访问携带token进行认证
'书籍信息
'前端网页->后端servlet:携带token进行认证
'后端servlet<-数据库:token认证有效,返回所有书籍信息
'后端servlet->前端网页:写入书籍信息
'前端网页->后端servlet:携带token进行认证
'后端servlet->数据库:认证有效,发送用户名查询用户信息
'数据库->后端servlet:返回查询数据
'后端servlet->前端网页:写入查询数据

'前端网页->后端servlet:携带token进行认证
'后端servlet->数据库:认证有效,发送用户名查询用户订单信息
'数据库->后端servlet:返回查询数据
'后端servlet->前端网页:写入查询数据

'前端网页->后端servlet:携带token进行认证
'后端servlet->数据库:认证有效,发送用户名查询用户购物车信息
'数据库->后端servlet:返回查询数据
'后端servlet->前端网页:写入查询数据

前端网页->后端servlet:携带token进行认证
数据库->后端servlet:token认证有效，返回所有用户信息
后端servlet->前端网页:返回的书籍写入到前端页面中


@enduml

